# KiWIS Basic Example
In this notebook we show how to create a connection to KiWIS and access basic data

In [1]:
from kisters.water.time_series.kiwis import KiWIS

In [2]:
# Create kiwis connection
kiwis = KiWIS(kiwis_uri="http://kiwis.kisters.de/KiWIS2/KiWIS", datasource=0, create_pandas=True)

In [3]:
kiwis.getStationList()

,station_id,station_latitude,station_longitude,station_name,station_no
0,23438,50.7827,6.0941,Aachen,00003
1,26148,,,Aachen,00003
2,17446,,,Aachen HQ ground water,AHQGW
3,17450,,,Aachen HQ surface water,AHQSW
4,26159,,,Aachen-Orsbach,15000
5,24642,50.7983,6.0244,Aachen-Orsbach,15000
6,23439,48.922,9.9129,Abtsgmünd-Untergröningen,00020
7,23440,49.7175,10.9101,Adelsdorf (Kläranlage),00029
8,28319,45.3531,8.61626,Agogna,IT_RV_01-053055
9,26151,,,Ahaus,07374
10,24589,52.0814,6.941,Ahaus,07374
11,28288,58.1236,26.9578,Ahja_2,EE_RV_SJA6031004
12,26154,,,Aholfing,00046
13,23442,48.945,12.4639,Aholfing,00046
14,23443,49.4997,9.5439,Ahorn-Eubigheim,00047
15,23444,52.585,13.5634,Ahrensfelde,00053
16,28300,64.06,25.54,Aittokylä,FI11071023
17,28318,45.3183,11.2672,Albaredo d'adige ponte di Albaredo,IT_RV_I_N001_VE05
18,23445,48.2156,8.9784,Albstadt-Badkap,00071
19,23446,48.6159,13.0506,Aldersbach-Kriestorf,00073
20,24583,51.9644,9.8072,Alfeld,07367
21,23447,52.4853,7.9126,Alfhausen,00078
22,28336,43.60694,13.03576,Alluvioni Vallive del Fiume Misa e dei suoi tr...,IT11C_AV_MIS
23,23448,51.095,11.0479,Alperstedt,00087
24,23449,50.7446,9.345,Alsfeld-Eifa,00091
25,23450,51.189,8.4671,Altastenberg,00098
26,23453,49.4053,12.2852,Altendorf,00118
27,23455,47.8342,10.8667,Altenstadt,00125
28,23456,49.7283,9.7692,Altertheim-Oberaltertheim,00130
29,24203,48.1479,9.4596,"Altheim, Kreis Biberach",04189
...,...,...,...,...,...
1413,95377,-28.98063278,153.4044037,WQM_Demo_Station_1,WQM_Demo_Station_1
1414,95378,-29.00035477,153.4321747,WQM_Demo_Station_2,WQM_Demo_Station_2
1415,95379,-28.87007523,153.5763397,WQM_Demo_Station_3,WQM_Demo_Station_3
1416,95380,-29.35368729,153.3182983,WQM_Demo_Station_4,WQM_Demo_Station_4
1417,95381,-29.3536874,153.318299,WQM_Demo_Station_5,WQM_Demo_Station_5
1418,24453,52.6167,14.2333,Wriezen,05697
1419,24464,54.6928,8.5271,Wrixum/Föhr,05732
1420,24454,51.5427,8.7784,Wünnenberg-Eilern,05699
1421,24595,50.0315,11.9745,Wunsiedel-Schönbrunn,07394
1422,24457,52.4605,9.4311,Wunstorf,05715
1423,24458,51.2256,7.1052,Wuppertal-Buchenhofen,05717
1424,24460,48.3569,12.7678,Wurmannsquick-Egelsberg,05721
1425,24455,49.7703,9.9577,Würzburg,05705
1426,24456,49.1296,9.4945,Wüstenrot-Oberheimbach,05711
1427,24524,52.3613,12.3867,Wusterwitz,06265
1428,24462,52.7605,14.2173,Wustrow,05729
1429,24463,47.6783,8.3801,Wutöschingen-Ofteringen,05731
1430,24465,51.697,6.3974,Xanten,05733
1431,28372,50.8921,18.9107,Zakrzew,PL2240601424000014
1432,24466,52.9664,13.3268,Zehdenick,05745
1433,24467,51.0314,12.1495,Zeitz,05750
1434,24468,49.8711,6.7079,Zemmer (Forsthaus Mülchen),05758
1435,28241,47.17541,11.8358,Zentralzone [DBJ],ATGK100010
1436,24469,53.0704,10.8831,Zernien,05762
1437,23604,52.2994,11.6733,Zielitz,00874
1438,24472,50.7314,13.7516,Zinnwald-Georgenfeld,05779
1439,24473,47.4209,10.9847,Zugspitze,05792
1440,24474,48.4217,10.5945,Zusmarshausen,05793
1441,24476,49.028,13.2385,Zwiesel,05800
1442,28317,39.8323,9.50323,20-0066-CF001800-ST01,IT_RV_20-0066-CF001800-ST01

In [4]:
kiwis.getTimeseriesList(station_id=23438)

,parametertype_id,parametertype_name,station_id,station_name,station_no,ts_id,ts_name
0,523,Precip,23438,Aachen,00003,3351042,0 Stundenwerte
1,523,Precip,23438,Aachen,00003,3352042,2 Monatssumme
2,523,Precip,23438,Aachen,00003,3354042,1 Tageswerte
3,523,Precip,23438,Aachen,00003,3353042,3 Jahressume

In [5]:
df = kiwis.getTimeseriesValues(ts_id=7411042, from_='2018-01-01', to='2018-01-02')

In [6]:
df

,columns,data,rows,ts_id
0,"Timestamp,Value","[[2018-01-01T00:00:00.000+01:00, 0.4], [2018-0...",48,7411042

In [7]:
df.data.values

array([list([['2018-01-01T00:00:00.000+01:00', 0.4], ['2018-01-01T01:00:00.000+01:00', 0.1], ['2018-01-01T02:00:00.000+01:00', 0.0], ['2018-01-01T03:00:00.000+01:00', 0.0], ['2018-01-01T04:00:00.000+01:00', 0.0], ['2018-01-01T05:00:00.000+01:00', 0.0], ['2018-01-01T06:00:00.000+01:00', 0.0], ['2018-01-01T07:00:00.000+01:00', 0.4], ['2018-01-01T08:00:00.000+01:00', 0.0], ['2018-01-01T09:00:00.000+01:00', 0.0], ['2018-01-01T10:00:00.000+01:00', 0.0], ['2018-01-01T11:00:00.000+01:00', 0.0], ['2018-01-01T12:00:00.000+01:00', 0.0], ['2018-01-01T13:00:00.000+01:00', 0.1], ['2018-01-01T14:00:00.000+01:00', 0.0], ['2018-01-01T15:00:00.000+01:00', 0.0], ['2018-01-01T16:00:00.000+01:00', 0.0], ['2018-01-01T17:00:00.000+01:00', 0.0], ['2018-01-01T18:00:00.000+01:00', 0.0], ['2018-01-01T19:00:00.000+01:00', 0.0], ['2018-01-01T20:00:00.000+01:00', 1.0], ['2018-01-01T21:00:00.000+01:00', 1.0], ['2018-01-01T22:00:00.000+01:00', 0.3], ['2018-01-01T23:00:00.000+01:00', 0.0], ['2018-01-02T00:00:00.000+01:00', 1.0], ['2018-01-02T01:00:00.000+01:00', 0.6], ['2018-01-02T02:00:00.000+01:00', 0.6], ['2018-01-02T03:00:00.000+01:00', 0.9], ['2018-01-02T04:00:00.000+01:00', 0.8], ['2018-01-02T05:00:00.000+01:00', 0.3], ['2018-01-02T06:00:00.000+01:00', 0.5], ['2018-01-02T07:00:00.000+01:00', 0.2], ['2018-01-02T08:00:00.000+01:00', 0.0], ['2018-01-02T09:00:00.000+01:00', 0.1], ['2018-01-02T10:00:00.000+01:00', 0.0], ['2018-01-02T11:00:00.000+01:00', 0.0], ['2018-01-02T12:00:00.000+01:00', 0.5], ['2018-01-02T13:00:00.000+01:00', 0.3], ['2018-01-02T14:00:00.000+01:00', 0.0], ['2018-01-02T15:00:00.000+01:00', 0.0], ['2018-01-02T16:00:00.000+01:00', 0.0], ['2018-01-02T17:00:00.000+01:00', 0.0], ['2018-01-02T18:00:00.000+01:00', 0.1], ['2018-01-02T19:00:00.000+01:00', 0.0], ['2018-01-02T20:00:00.000+01:00', 0.0], ['2018-01-02T21:00:00.000+01:00', 0.0], ['2018-01-02T22:00:00.000+01:00', 0.0], ['2018-01-02T23:00:00.000+01:00', 0.0]])],
      dtype=object)